### ISSUE TITLE
erroneous newline

### ISSUE THREAD

**Issue by fauman** [EBISPOT/gwas-user-requests#1]
There appears to be an erroneous newline (\n) in the gwas_catalog_v1.0.2-associations_e100_r2020-09-09.tsv download file, line 143081, in the p_value_text field:

between: **(parieto-frontal low theta coherence at P8-P4-F8-F4)**
and **coherence**

https://www.ebi.ac.uk/gwas/variants/rs151174000

**Comment by ljwh2** [comment]
Thanks for alerting us to this, we are looking into it

**Comment by mcerezof** [comment]
The line also appeared in the uploaded spreadsheet of associations for the study, however it passed the validation and it does not appear in the curation interface.
The entry has been edited and the extra line should disappear for the next release
![Screenshot 2020-10-08 at 17 30 08](https://user-images.githubusercontent.com/12908693/95487246-fde9e380-098b-11eb-831d-739eeca79e2d.png)

**Comment by ljwh2** [comment]
Fixed in latest data release
