### ISSUE TITLE
Duplicate rows in GWAS summary stats file

### ISSUE THREAD

**Issue by mcgml** [EBISPOT/gwas-user-requests#19]
Hi

Please see this issue re duplicate rows in GWAS summary stats file

https://github.com/MRCIEU/gwas-vcf-specification/issues/10

Many thanks
Matt

**Comment by jdhayhurst** [comment]
Hi Matt,

I've reprocessed the file and replaced the files. It looks like there was a formatting error. Please let me know if there are still issues with the files.
Thanks
