### ISSUE TITLE
GCST006287: GWAS for adolescent idiopathic scoliosis is problematic?

### ISSUE THREAD

**Issue by dhimmel** [EBISPOT/gwas-user-requests#2]
https://www.ebi.ac.uk/gwas/studies/GCST006287 contains associations for adolescent idiopathic scoliosis from:

> **The coexistence of copy number variations (CNVs) and single nucleotide polymorphisms (SNPs) at a locus can result in distorted calculations of the significance in associating SNPs to disease**   
Jiaqi Liu, Yangzhong Zhou, Sen Liu, Xiaofei Song, Xin-Zhuang Yang, Yanhui Fan, Weisheng Chen, Zeynep Coban Akdemir, Zihui Yan, Yuzhi Zuo, … Nan Wu  
*Human genetics* (2018-07) <https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6200315/>   
DOI: [10.1007/s00439-018-1910-3](https://doi.org/10.1007/s00439-018-1910-3) · PMID: [30019117](https://www.ncbi.nlm.nih.gov/pubmed/30019117) · PMCID: [PMC6200315](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6200315)

The GWAS Catalog page has 1317 associations for this study, despite the small discovery sample size of 196 cases and 303 controls. The are a dozen or so SNPs whose association p-value is smaller than 1 x 10<sup>-100</sup>. Given the title of the study and these implausible results, I wonder if these associations are the "distorted calculations of the significance" mentioned in the title?

Is there a way to flag studies like this? Or should it be removed from the GWAS Catalog entirely? The high number of associations is likely to have a major impact on analysis that use the GWAS Catalog as a record of all disease-SNP associations.

**Comment by dhimmel** [comment]
Quote from the main text:

> To verify our findings, we further performed a genome-wide association study of 196 AIS patients and 303 subjects without AIS. In the total of 27,096 SNPs with significant difference (p<0.05, Table S3) between cases and controls, 585(2.16%) SNPs were identified overlapping with CNVs in the same region either in the patients or controls (Table S4). To avoid the bias of CNV to disease-associated SNP analysis between the cases and controls, we assessed the influence of the CNVs on the significance of their overlapping SNPs.

It looks like the results added to the GWAS Catalog are from Table S3 ([download link](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6200315/bin/NIHMS987877-supplement-S3.xlsx))

> Table S3. The total of 27,096 SNPs with significant difference between 196 AIS cases and 303 control subjects in the AIS genome-wide association study (XLSX 1651 KB)

Here are the top rows:


CHR | SNP | A1 | A2 | TEST | AFF | UNAFF | CHISQ | DF | p value
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
7 | rs6964752 | A | G | ALLELIC | 391//1 | 0//622 | 1010 | 1 | 1.34E-221
2 | rs41497646 | G | A | ALLELIC | 367//1 | 0//614 | 977.7 | 1 | 1.24E-214
4 | rs41337747 | A | G | ALLELIC | 350//0 | 0//618 | 968 | 1 | 1.62E-212
16 | rs1051432 | C | G | ALLELIC | 388//0 | 8//604 | 967 | 1 | 2.69E-212
14 | rs3007163 | A | G | ALLELIC | 163//1 | 9//553 | 671.5 | 1 | 4.67E-148
1 | rs41320847 | G | A | ALLELIC | 2//0 | 0//626 | 628 | 1 | 1.36E-138
13 | rs3847988 | C | A | ALLELIC | 2//0 | 0//624 | 626 | 1 | 3.71E-138

**Comment by aoifemcm** [comment]
Dear Daniel,
Firstly, let me apologise for the delay in getting back to you.

I've had a look at this study, and it looks to be an interesting case.  I think it probably is the case the the very small p-values reflect the issue that the authors are highlighting.  That is that the presence of SNPs in CNV regions can lead to their incorrect genotyping, and therefore inflated association p-values. 

However, I don't think it's appropriate to remove the study from the Catalog, not least because this issue only affects a couple of loci. The paper otherwise fulfils our eligibility criteria.  Our philosophy is to present the data in the paper alongside information that will allow our users to make their own judgements about the quality and utility of the data, as you have done.

That said, it might be interesting to consider automatically flagging SNPs that co-localise with CNVs, and we may consider this for future development.  Thank you for bringing this to our attention.  I'll have a look at your other query now.

Best wishes,
Aoife

on behalf of the GWAS Catalog team
@GWASCatalog

**Comment by dhimmel** [comment]
Quoting from https://github.com/EBISPOT/gwas-user-requests/issues/3#issuecomment-737234274

> In relation to the other study you queried, GCST006287, the authors there did not supply chromosomal co-ordinates, so we could not filter associations for independence (based on 100kb distance) as we normally would.

In combination with:

> the presence of SNPs in CNV regions can lead to their incorrect genotyping, and therefore inflated association p-values... this issue only affects a couple of loci.

So the current thinking is that there are two issues leading to the large number of associations (1317):

1. some association p-values are inflated for SNPs located in CNV regions.
2. GWAS Catalog did not filter filter associations to one-per-locus, since the authors did not provide genomic coordinates for SNPs. So presumably the 1317 associations could be grouped into a much smaller number of independent loci?

Downloading the association CSV table (and converting to excel so I can upload it to this issue), I get a list of the 1317 associations: [studies_GCST006287-associations-2020-12-2.xlsx](https://github.com/EBISPOT/gwas-user-requests/files/5630428/studies_GCST006287-associations-2020-12-2.xlsx), which looks like:

Variant and risk allele | P-value | Mapped gene | Trait(s) | Study accession | Location
-- | -- | -- | -- | -- | --
rs7980288-<b>?</b> | 1 x 10-7 | A2M | adolescent idiopathic scoliosis | GCST006287 | 12:9102864
rs12321593-<b>?</b> | 1 x 10-6 | AACS | adolescent idiopathic scoliosis | GCST006287 | 12:125129202
rs9893173-<b>?</b> | 7 x 10-10 | ABCA9-AS1, ABCA9 | adolescent idiopathic scoliosis | GCST006287 | 17:68977338

Here's a snippet of Python code to count the distinct mapped-genes across all associations:

```python
import pandas
import itertools
path = "studies_GCST006287-associations-2020-12-2.xlsx"
assoc_df = pandas.read_excel(path)
distinct_genes = sorted(set(itertools.chain.from_iterable(assoc_df["Mapped gene"].str.split(", "))))
len(distinct_genes)
```

The total number of distinct mapped genes is 1758. This high number makes me think the associations are not necessarily all clustered in a small number of independent loci. The Manhattan plot from [Open Targets Genetics](https://genetics.opentargets.org/study/GCST006287) shows genome-wide significant associations scattered across the genome:

![image](https://user-images.githubusercontent.com/1117703/100897630-e0b62a80-348d-11eb-81e7-e278ea1995ae.png)

 > I don't think it's appropriate to remove the study from the Catalog

I definitely understand not wanting to remove the study from the Catalog, since it still might be useful for some applications. However, I worry that the most common application of the Catalog is to link gene to disease. And when a 499-subject study ends up errantly implicating 1000s of genes with a disease, it can have an undue influence on downstream analyses. The inclusion of this study in Open Targets is emblematic of the problem: OTG extracts 677 variants mapped to 1539 genes from this study, indicating a large number of possible pharmaceutical targets for adolescent idiopathic scoliosis (unless we can somehow separate these poor-quality associations from higher-quality associations).

So I wonder if there's a flag that GWAS Catalog could set to indicate a study or association does not meet certain standards for applications looking to integrate associations between studies. Or perhaps the community could maintain a list of studies that are suspect? I don't have a great solution, but just know that every user implementing solutions for themselves won't scale. So thanks for creating this forum for discussion!

**Comment by aoifemcm** [comment]
Dear Daniel,
I completely agree that both of these publications have suspiciously high numbers of associations given the sample sizes, and the reasons for these aren't clear.  For now, we are happy that we've provided enough information for you to flag them yourself so you can investigate further.  We attach a lot of weight to user input like yours and we will take your suggestions on board when we discuss future developments.  Please don't hesitate to contact us if you have any future questions or comments.  
Best wishes,
Aoife
