### ISSUE TITLE
Investigate why there are invalid values in published sumstats

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-user-requests#22]
GCST007236, looks very strange. E.g. the beta and SE values look strange, p values are outside the range 0 - 1, etc. Could you have a look?
It's this file:
ftp://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST007001-GCST008000/GCST007236/harmonised/25751625-GCST007236-EFO_0000305.h.tsv.gz

- these sumstats predate the validation/submission pipeline but should be investigated and fixed

**Comment by jdhayhurst** [comment]
Hi @buniello I think this dataset needs to be reformatted - please let me know if I can help

**Comment by buniello** [comment]
@jdhayhurst I have re-formatted the original file and values make sense now. I could not figure out what happened with previous processing - the original file contains 61 columns and something must have gone wrong with the previous formatting tool.

new file: formatted_icogs_bcac_public_results_euro.build37.tsv in preanalysis/buniello

**Comment by jdhayhurst** [comment]
queued for harmonisation 
once completed - release formatted and harmonised data

**Comment by jdhayhurst** [comment]
released
