### ISSUE TITLE
Missing met-d-XXL_VLDL_TG from harmonised sumstats

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-user-requests#23]
OTAR issue - this dataset was accidentally skipped from conversion from vcf to tsv. It needs to be converted, formatted, harmonised and sent to OTAR

**Comment by buniello** [comment]
@jdhayhurst file is now formatted and in preanalysis/buniello -- formatted_met-d-XXL_VLDL_TG.tsv

**Comment by jdhayhurst** [comment]
queued for harmonisation

**Comment by jdhayhurst** [comment]
completed and released to otar ftp
