### ISSUE TITLE
Investigate missing harmonised files

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-user-requests#27]
User reported that some harmonised files may be absent from the FTP, when they should be public.

see for details: https://docs.google.com/spreadsheets/d/1H9zJAINFisPTY88lvcQzJdmM8o33CzzQdMdTVKuN7GI/edit#gid=0

**Comment by aoifemcm** [comment]
Reported from another user (Remo Monti, Intervene) http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST004001-GCST005000/GCST004773/

**Comment by jdhayhurst** [comment]
It looks like for the majority of cases, the files are not harmonised because the original summary stats pre-date our submission app and therefore require pre-harmonisation formatting. 
Due to the volume of formatting (ultimately a manual process), we need to process the studies according to a prioritisation queue and these studies have simply not reached the front of the queue yet. The one exception is `GCST90013405`, which has been harmonised and exists at the path below on the FTP.
```
accessionID   harmonised  comments
GCST90013405  TRUE        GCST90013405/harmonised/33972514-GCST90013405-EFO_0004735.h.tsv.gz
GCST006900    FALSE       not formatted
GCST008124    FALSE       not formatted
GCST008125    FALSE       not formatted
GCST008127    FALSE       not formatted
GCST008129    FALSE       not formatted
GCST009107    FALSE       not formatted
GCST009655    FALSE       not formatted
GCST009660    FALSE       not formatted
GCST004233    FALSE       not formatted
GCST009150    FALSE       not formatted
GCST004237    FALSE       not formatted
GCST009152    FALSE       not formatted
GCST009127    FALSE       not formatted
GCST004773    FALSE       not formatted
```
