### ISSUE TITLE
GCST008413: study on acute myeloid leukemia is problematic?

### ISSUE THREAD

**Issue by dhimmel** [EBISPOT/gwas-user-requests#3]
GWAS Catalog study [GCST008413](https://www.ebi.ac.uk/gwas/studies/GCST008413) corresponds to:

> **Genome-wide haplotype association study identify the FGFR2 gene as a risk gene for Acute Myeloid Leukemia**   
Hongchao Lv, Mingming Zhang, Zhenwei Shang, Jin Li, Shanshan Zhang, Duan Lian, Ruijie Zhang  
*Oncotarget* (2016-11-26) <https://doi.org/f9p89x>   
DOI: [10.18632/oncotarget.13631](https://doi.org/10.18632/oncotarget.13631) · PMID: [27903959](https://www.ncbi.nlm.nih.gov/pubmed/27903959) · PMCID: [PMC5352368](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5352368)

The number of associations seems problematic given the small sample size:

- Discovery sample description: 175 European ancestry cases, 218 European ancestry controls
- 1744 associations

**Comment by dhimmel** [comment]
I noticed this as an outlier when plotting the number of variants discovered versus the sample size for studies in OpenTargets Genetics:

> ![](https://user-images.githubusercontent.com/1117703/97900359-87c96a00-1d08-11eb-8c83-b66303db2250.png)

OpenTargets Genetics includes GWAS Catalog data and performs some processing, so while the exact numbers might be slightly different, the outliers are likely the same. Note that OTG has remove associations using a genome wide significance threshold of 5e-08.

Note I reported one of the other outlier studies in #2.

**Comment by aoifemcm** [comment]
Dear Daniel,

I've had a look at this study. I can't see any problem with it that would cause us to remove it and the data are as presented in the paper.  I'd note that the study looks at multi-SNP haplotypes (See table S2), with each separate haplotype genotype for the same variants presented separately.  This leads to an inflation of the number of associations for the same variants.  For example:

chr21 | rs12482962,rs2837107, | 41021979 | 41025557 | TT
chr21 | rs12482962,rs2837107, | 41021979 | 41025557 | CT

And now that I understand you are also interested in pure numbers of significant associations:  In relation to the other study you queried, GCST006287, the authors there did not supply chromosomal co-ordinates, so we could not filter associations for independence (based on 100kb distance) as we normally would.  This is another factor that would increase the number of apparent associations in the Catalog. We also do not filter haplotype data.

I hope that helps.  Again, thanks for bringing these to our attention, we welcome your input.
Aoife

**Comment by dhimmel** [comment]
Thanks for taking a look.

>  I'd note that the study looks at multi-SNP haplotypes (See [table S2](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5352368/bin/oncotarget-08-7891-s003.xls)), with each separate haplotype genotype for the same variants presented separately.

Makes sense that the lead-snp filter (is that the right term) doesn't work for associations with multi-SNP haplotypes.

I don't think that's the entire problem, since the Manhattan plot [from OTG](https://genetics.opentargets.org/study/GCST008413) shows associations throughout the genome:

![image](https://user-images.githubusercontent.com/1117703/100900101-7d79c780-3490-11eb-8f96-c5f2f6dae1c0.png)

**Comment by aoifemcm** [comment]
See response in https://github.com/EBISPOT/gwas-user-requests/issues/2
