### ISSUE TITLE
studies for submission 6130d5e6088ad000014c5e72 not being displayed on landing page

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-user-requests#30]
the search works, the tables work but the study landing pages do not. 
The sample data did not import correctly @sajo-ebi and @jdhayhurst will need to manually fix this one

**Comment by jdhayhurst** [comment]
Reassigned sample data to studies in SPOTREL.
Based on https://www.ebi.ac.uk/seqdb/confluence/pages/viewpage.action?pageId=57282013 - created snapshot, then refreshed FALLBACK and SPOTPUB

**Comment by sajo-ebi** [comment]
Data has been refreshed in Spotpub & the issue has been fixed & validated by the user
