### ISSUE TITLE
Potential wrong value in the p-value annotation column

### ISSUE THREAD

**Issue by mpage21** [EBISPOT/gwas-user-requests#31]
GCST002299 has the value 0.66 in the P-value annotation column for rs926070-A --> this seems like it should be in the RAF column instead
GCST011066 has the value 0.13 in the P-value annotation column for rs77462941-C --> also seems like it should be in the RAF column

**Comment by ljwh2** [comment]
hi @mpage21, what file are you seeing this error in?

**Comment by eks-ebi** [comment]
@ljwh2 This does seem to be a simple curation error - I am checking the original papers to confirm if it is indeed the RAF that has been put in the wrong field

**Comment by eks-ebi** [comment]
Confirmed: the RAF was incorrectly entered into the P-value annotation field. This has now been corrected in our database and the change can be included in today's data release.

**Comment by mpage21** [comment]
Thank you!
