### ISSUE TITLE
remove GCST003155 from sumstats db

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-user-requests#36]
GCST003155 is in the sumstats db but is a duplicate of GCST003156. It should be removed

**Comment by jdhayhurst** [comment]
completed and updated documentation on deletion procedure:
https://www.ebi.ac.uk/seqdb/confluence/display/GOCI/Study+Loading

**Comment by jdhayhurst** [comment]
The sumstats api no longer has records for GCST003155. @buniello please can you confirm that all looks fine from the GWAS catalog website?

**Comment by buniello** [comment]
The API link is not visible anymore for GCST003155. All good @jdhayhurst
