### ISSUE TITLE
Reopening the status for PMID 34265237 (submission ID: 6139296a09113d0001e14c34)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/gwas-user-requests#37]
The metadata and top association was curated through depo app and now it needs to be reopened to submit summary stat

**Comment by sajo-ebi** [comment]
Discussed with @Santhi1901 , the study  needs to be published for the sumstats to be submitted which will be done as part of Data release

**Comment by Santhi1901** [comment]
@sajo-ebi It needs to be reopened to add sumstat the status of study is shown as 'CLOSED'

**Comment by sajo-ebi** [comment]
@Santhi1901 Please confirm if this PMid still needs to be open?

**Comment by Santhi1901** [comment]
@sajo-ebi yes I need to add sumstat to the PMID. The PMID is already showing OPEN FOR SUMMARY STATISTICS SUBMISSION in deposition tool

**Comment by Santhi1901** [comment]
@sajo-ebi I am not able to download submission form for this. https://www.ebi.ac.uk/gwas/deposition/submission/6139296a09113d0001e14c34

**Comment by sajo-ebi** [comment]
@Santhi1901 since this ID is already submitted , the submission form can't be downloaded , for creating a sumstats submission you need to create sum stats type for the Pmid

**Comment by Santhi1901** [comment]
@sajo-ebi error is displayed while trying to download submission form. Error: There is a fault on our end. Please contact gwas-subs@ebi.ac.uk for help. 
https://www.ebi.ac.uk/gwas/deposition/submission/61b78a74911f5a0001550987

**Comment by sajo-ebi** [comment]
@Santhi1901 , there was some issues with Deposition Sync & the studies hadn't synced at Deposition app side , have manually added the entries in Depo DB .Kindly  create a fresh sum stats submission , Have opened the PMID for sum stats only submission , you should be able to download the form for a fresh submission

**Comment by Santhi1901** [comment]
@sajo-ebi now there is no download submission button on that page

**Comment by sajo-ebi** [comment]
@Santhi1901 can you provide the new submission details which you have created where the download button is missing

**Comment by Santhi1901** [comment]
@sajo-ebi 
https://www.ebi.ac.uk/gwas/deposition/submissions

https://www.ebi.ac.uk/gwas/deposition/submission/6139296a09113d0001e14c34

**Comment by ljwh2** [comment]
@Santhi1901 could you please update on this ticket, is the submission in the same state?

**Comment by Santhi1901** [comment]
yes it is in the same state. I still can't download the submission form and can't upload summary statistics

**Comment by Santhi1901** [comment]
@sajo-ebi can you reopen the pmid so that I can submit both metadata and sumstat together?

**Comment by sajo-ebi** [comment]
@Santhi1901 before I open the Pmid do I need to delete all previous submissions? Has the GCST been published for this

**Comment by Santhi1901** [comment]
@sajo-ebi  yes, the GCST is published. If we delete the submission and again do it with sumstats, will you be able to change the GCST to the original one? It has 1 study

**Comment by sajo-ebi** [comment]
@Santhi1901 yes I cam , if you have the GCST handy , I can delete all the submissions associated with this pmId , I think we have 3

**Comment by Santhi1901** [comment]
@sajo-ebi I've only one study associated with this PMId GCST90027266. you can delete this and reopen the submission

**Comment by sajo-ebi** [comment]
@Santhi1901 The submission has been deleted & Pmid has opened again

**Comment by Santhi1901** [comment]
thanks @sajo-ebi

**Comment by Santhi1901** [comment]
@sajo-ebi when I search for this pmid in the deposition app, status shown is 'OPEN FOR SUMMARY STATISTICS SUBMISSION' not 'OPEN FOR SUBMISSION'. But when I check the pmid under 'Active submission', no submissions is seen.
<img width="1014" alt="Screenshot 2022-06-27 at 9 23 11 am" src="https://user-images.githubusercontent.com/57477790/175895114-dfc0d81d-372d-4817-a2c7-200b429a1eb2.png">
<img width="1014" alt="Screenshot 2022-06-27 at 9 28 04 am" src="https://user-images.githubusercontent.com/57477790/175895122-d7d976f4-4d7b-406f-9b8d-87b57e6f9a37.png">

**Comment by sajo-ebi** [comment]
@Santhi1901 probably it was changed by DepoSync , changed the status , it is Open for Submission

**Comment by sajo-ebi** [comment]
@Santhi1901 please confirm if this can be closed

**Comment by Santhi1901** [comment]
@sajo-ebi yes, this can be closed
