### ISSUE TITLE
Update to submission template schema needed - exome sequencing technology

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/gwas-user-requests#39]
When attempting to upload submission template with genotyping technology 'Exome-wide sequencing' to match existing option in Curation App dropdown menu...

![Screenshot 2021-10-26 at 15.26.07.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/2b7fb7a6-12f8-4240-8b98-5d2bc6029a07)

...an error is returned: 
Errors:
Studies: Column 'Genotyping technology' in row(s) [5] contains incorrect value. Accepted values are: 'Genome-wide genotyping array; Targeted genotyping array; Exome genotyping array; Whole genome sequencing'

**Comment by jdhayhurst** [comment]
added 'Exome-wide sequencing' to the genotyping technology list in the template services schema. Bumped schema version. @earlEBI it's available for testing in sandbox.

**Comment by earlEBI** [comment]
working well, thank you.

**Comment by jdhayhurst** [comment]
deployed to prod
