### ISSUE TITLE
Saori Sakaue large submission status: import in progress 

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/gwas-user-requests#40]
Submission 609c44af4e974a0001bec83d
Author submission for 440 studies and sumstats files. 

Curators added associations (~17k) in the DepoCuratioin App. 

Was pushed through DepoCuration validation stage by Developers as the sumstats endpoint no longer existed. 

I clicked import in the Curation App around Wednesday 13th October, but the status remains 'import in progress' on 18th October. 

Submission needs to be published to Catalog before the next data release can go ahead.

**Comment by sajo-ebi** [comment]
@earlEBI unfortunately there was an deployment last Thursday for Curation App  that caused the Import process to end abruptly , as part of the last deployment the mapping pipeline step which was consuming  the most time has been removed , as it is being run as standalone manner & not needed during Import, this should speed up the import process . I will update the submission to a state where it can  be imported again

**Comment by earlEBI** [comment]
@sajo-ebi thanks, import worked except unfortunately none of the EFOs have imported. Edit: I think I see why, the header had a missing space between 'mapped' and 'trait'

**Comment by sajo-ebi** [comment]
The submission has been imported successfully & has been validated
