### ISSUE TITLE
Error getting directory bin for FTP site

### ISSUE THREAD

**Issue by ConnorBarnhill** [EBISPOT/gwas-user-requests#45]
Looking at this study: https://www.ebi.ac.uk/gwas/studies/GCST90080000
The link to download the full summary statistics from FTP gives a 404 error. This looks to be an error with the javascript function that gets the directory bin from the GCST id. Note that the FTP url is http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90080001-GCST90081000/GCST90080000

The GCST is mistakenly assigned bin 'GCST90080001-GCST90081000', when it should be bin 'GCST90079001-GCST90080000'. Manually directing to the correct bin does not lead to a 404 error:
http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90079001-GCST90080000/GCST90080000/

**Comment by jdhayhurst** [comment]
Closing as this was resolved by this ticket: https://github.com/EBISPOT/gwas-ui/issues/245
