### ISSUE TITLE
Sumstats file for GCST90088598 on FTP is truncated

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-user-requests#48]
1) Locate reason why GCST90088598 on FTP is truncated
2) If possible, fix GCST90088598 on FTP
3) Check the rest of the files from that submission and fix accordingly

**Comment by ljwh2** [comment]
Info from Annalisa: The user Alexander Guojonsson has identified a problem with one of his submitted files and has uploaded a replacement file onto our private FTP. This now needs to be moved onto the public FTP.

private FTP Directory: Guðjónsson_GCST90088598
file hecksum: 1ade547
public FTP directory: GCST90088001-GCST90089000/GCST90088598/

**Comment by jdhayhurst** [comment]
Affected studies and files:
'GCST90086701', 'somamer.11354_21_3.glm.linear.tsv'
'GCST90087682', 'somamer.13959_7_3.glm.linear.tsv'
'GCST90088076', 'somamer.2796_62_2.glm.linear.tsv'
'GCST90088598', 'somamer.4140_3_2.glm.linear.tsv'
'GCST90088699', 'somamer.4464_10_2.glm.linear.tsv'
'GCST90088852', 'somamer.4992_49_1.glm.linear.tsv'
'GCST90088938', 'somamer.5117_14_3.glm.linear.tsv'
'GCST90089314', 'somamer.6237_11_3.glm.linear.tsv'
'GCST90089837', 'somamer.7795_14_3.glm.linear.tsv'
'GCST90089992', 'somamer.8021_59_3.glm.linear.tsv'
'GCST90090046', 'somamer.8093_13_3.glm.linear.tsv'
'GCST90090213', 'somamer.8475_15_3.glm.linear.tsv'
'GCST90090373', 'somamer.8903_1_3.glm.linear.tsv'
'GCST90090428', 'somamer.8985_13_3.glm.linear.tsv'
'GCST90090448', 'somamer.9014_18_3.glm.linear.tsv'
'GCST90090540', 'somamer.9183_7_3.glm.linear.tsv'
'GCST90090601', 'somamer.9277_16_3.glm.linear.tsv'
'GCST90090700', 'somamer.9457_3_3.glm.linear.tsv'

**Comment by buniello** [comment]
may i communicate the list above to the user? @jdhayhurst

**Comment by jdhayhurst** [comment]
replaced files from originals - suspected sync issue.
update md5sums

**Comment by buniello** [comment]
HI @jdhayhurst @ljwh2 , the user Alexander Gudjonsson has observed file truncation again for the files below - which include the one we have updated for him. I know you have discussed the issue during the iteration meetings.
Please see text below:

I see that the file GCST90088598
<http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90088001-GCST90089000/GCST90088598/>
has
been updated on the ftp server, but when I download it, the same issue
occurs. The file is cut off at the exact same location.
I also noticed that four other files were updated at the same time, today,
Feb. 16. The same issue occurs in all of them as well. Those are files:
GCST90088076
<http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90088001-GCST90089000/GCST90088076/>
GCST90088699
<http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90088001-GCST90089000/GCST90088699/>
GCST90088852
<http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90088001-GCST90089000/GCST90088852/>
GCST90088938
<http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90088001-GCST90089000/GCST90088938/>

Best regards,
Alexander.

**Comment by jdhayhurst** [comment]
I'm not sure what happened. The modified date on the files is not what I was expecting (too recent). 
I've redone the sync and the md5sums look correct and the files are not truncated: ```6a3f9395772c128e3bfb7347d6d448ee  GCST90086001-GCST90087000/GCST90086701/GCST90086701_buildGRCh37.tsv
da28dcb796e407848d015db48efc4c7b  GCST90087001-GCST90088000/GCST90087682/GCST90087682_buildGRCh37.tsv
fc3307cf03da61737b585b9ebdd6c7b3  GCST90088001-GCST90089000/GCST90088076/GCST90088076_buildGRCh37.tsv
1ade54716c1968f0983abac00a88dc01  GCST90088001-GCST90089000/GCST90088598/GCST90088598_buildGRCh37.tsv
2a473cd569f0395d87d04dd350979523  GCST90088001-GCST90089000/GCST90088699/GCST90088699_buildGRCh37.tsv
f62079be1c7769bc33414515b46cd651  GCST90088001-GCST90089000/GCST90088852/GCST90088852_buildGRCh37.tsv
11a7c67039cdd023dd8fec58df4429df  GCST90088001-GCST90089000/GCST90088938/GCST90088938_buildGRCh37.tsv
cc5e8b222d6ace8f7cbe0c0f975690a2  GCST90089001-GCST90090000/GCST90089314/GCST90089314_buildGRCh37.tsv
98cacd44dd7e67b26170a28b26e43e07  GCST90089001-GCST90090000/GCST90089837/GCST90089837_buildGRCh37.tsv
ea1c9228edffd68d83b2c60c408714d6  GCST90089001-GCST90090000/GCST90089992/GCST90089992_buildGRCh37.tsv
ef1f323ffe902dca65b71fdd93caf6a6  GCST90090001-GCST90091000/GCST90090046/GCST90090046_buildGRCh37.tsv
b0e00c993982bad82f757ec6bed9025f  GCST90090001-GCST90091000/GCST90090213/GCST90090213_buildGRCh37.tsv
9e9b348e0b2e64d2db1936a391c657e0  GCST90090001-GCST90091000/GCST90090373/GCST90090373_buildGRCh37.tsv
1400cd2b2dbad24279e551dd52f8239e  GCST90090001-GCST90091000/GCST90090428/GCST90090428_buildGRCh37.tsv
598e47b9508286d118543affdfc664cb  GCST90090001-GCST90091000/GCST90090448/GCST90090448_buildGRCh37.tsv
f13d0d00d8c5a986e35042cf276984c8  GCST90090001-GCST90091000/GCST90090540/GCST90090540_buildGRCh37.tsv
4ea32b443363d1b69dd9069c2861c964  GCST90090001-GCST90091000/GCST90090601/GCST90090601_buildGRCh37.tsv
f3964c620f1d8ebd0a8a196330dd43e0  GCST90090001-GCST90091000/GCST90090700/GCST90090700_buildGRCh37.tsv```
It may take a little while to come through on the FTP
