### ISSUE TITLE
rs1366200 in GCST002685 has a comma in its CI range instead of a period

### ISSUE THREAD

**Issue by mattcloward** [EBISPOT/gwas-user-requests#5]
See the below page:
https://www.ebi.ac.uk/gwas/variants/rs1366200

The CI is "[1.174-1,457]" but it should be "[1.174-1.457]"

Thank you!

**Comment by ljwh2** [comment]
Thanks for bringing this to our attention. I have removed the comma in the database and you should see the change in the public version after our next data release in mid January
