### ISSUE TITLE
OTAR reported harmonisation data issue to investigate

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-user-requests#52]
OTAR reporting failures for the following although the files exists:
GCST004292
GCST004293

This one has no data, although other GWAS from the same publication seem okay:
GCST006079

No data in harmonised file:
GCST90000181
GCST90011883
GCST90011881
GCST010116

No variants harmonised successfully:
GCST010763
GCST010764
GCST90093287
GCST90093288
GCST90011900

No alleles in original file - seems like variants couldn't be harmonised:
GCST004293
GCST004292

it looks like these 3 studies from 1 publication, which had their betas reversed, were just removed from sumstats?  I don't see them available anymore. (I guess the raw data isn't corrected?)
GCST001725
GCST001728
GCST001729

**Comment by jdhayhurst** [comment]
GCST004293 - Many variants dropped due to no alleles
GCST004292 - Many variants dropped due to no alleles
GCST006079 - Re-queued harmonisation
GCST90000181 - No other allele, cannot harmonise. Removed empty harmonised file
GCST90011883 - No other allele, cannot harmonise. Removed empty harmonised file
GCST90011881 - No other allele, cannot harmonise. Removed empty harmonised file
GCST010116 - formatting error, reformatted and re-queued for harmonisation
GCST010763 - @buniello this has alleles, please could you investigate?
GCST010764 - @buniello this has alleles, please could you investigate?
GCST90093287 - no alleles, cannot harmonise. Removed empty harmonised dir
GCST90093288 - no alleles, cannot harmonise. Removed empty harmonised dir
GCST90011900  - no alleles, cannot harmonise. Removed empty harmonised dir
GCST001725, GCST001728, GCST001729 - @buniello do you know if these sumstats were removed?

**Comment by buniello** [comment]
GCST010763 and GCST010764 alleles are not properly labeled in the sumstats file & in the paper. Therefore the curator who formatted files and curated paper (Aoife) decided not to extract alleles. I believe she also contacted the authors with no reply @jdhayhurst

**Comment by buniello** [comment]
GCST001725, GCST001728, GCST001729 from Jostins PMID 23128233 - the sumstats only hosted data for 25k SNPs and I was asked  to remove these datasets from FTP due to eligibility criteria @jdhayhurst

**Comment by buniello** [comment]
Linking this ticket to this additional one i have created upon Jeremy's requests:
https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/620

**Comment by jdhayhurst** [comment]
Thanks @buniello - this ticket is now complete as far as I can tell.
