### ISSUE TITLE
mis-labelled beta in GCST007799 and GCST007800 (PMID: 30929738)

### ISSUE THREAD

**Issue by mohdkarim** [EBISPOT/gwas-user-requests#53]
On checking source files provided by the [asthma study](https://europepmc.org/article/med/30929738) ([1](http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST007001-GCST008000/GCST007799/ADULT1_ADULT2_ONSET_ASTHMA.20180716.allchr.assoc.GC.gz), [2](http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST007001-GCST008000/GCST007800/CHILD_ONSET_ASTHMA.20180501.allchr.assoc.GC.gz)), it appears the `BETA` column is reporting odds ratios and not beta coefficients. 

Below is an example from GCST007799 (Adult-onset asthma) of the estimate for rs17668708 (one of the top SNPs reported in the paper's Table 3:

Code: `zcat ADULT1_ADULT2_ONSET_ASTHMA.20180716.allchr.assoc.GC.gz | sed '1p;/rs17668708/!d'`

Output: `SNP CHR BP ALLELE1 ALLELE0 A1FREQ INFO BETA SE P_BOLT_LMM_INF N SE_GC P_GC` 
`rs17668708 1 198640488 C T 0.892707 0.980384 1.09563 0.0135506 1.6e-11 327253 0.013671 2.381e-11` 

The mis-labelled beta is also present in GCST007800 (Childhood-onset asthma).

The error propagates to harmonised sumstats and all downstream analyses (e.g. colocalisation, mendelian randomization analyses) using the harmonised data.

**Comment by jdhayhurst** [comment]
Reformatting and harmonising so that what the author provided as "beta" will now be "odds_ratio" in the formatted files. Their original data will remain the same.

**Comment by jdhayhurst** [comment]
@mohdkarim, this has been completed. harmonised data have been released.
