### ISSUE TITLE
Harmonise sumstats for 35115689  

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-user-requests#54]
These summary statistics are in the pipeline at the formatting stage but have remained there. We need to figure out why they are not progressing through the pipeline and get them harmonised.

**Comment by ljwh2** [comment]
@earlEBI to investigate in the first instance

**Comment by earlEBI** [comment]
I'm afraid I can't see an obvious reason. [gwas-subs](https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=533468) suggests they got their [submission](https://www.ebi.ac.uk/gwas/deposition/submission/6141bc0a09113d0001e193ac) to go through themselves without help. I checked one file and the headers seem ok...

![Screenshot 2022-04-20 at 12 41 44](https://user-images.githubusercontent.com/61545198/164223275-24b5303f-e385-4c41-82f8-c6c57691f293.png)

**Comment by jdhayhurst** [comment]
I think I've identified and fixed the issue. Snakemake, which is managing this workflow, was exiting as soon as another independent job failed. There was a corrupt file that kept failing the pipeline, so even though these files are fine, they either never started or got terminated by snakemake.
