### ISSUE TITLE
Issue with setting the effect allele in 21297633

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-user-requests#56]
Email sent to gwas-info.

Adding content from email here to keep track - see email for more info:

> we think there is an issue with the data released through GWAS catalog regarding the study Anderson et al. 2011 -  PMID 21297633.
> 
> The original data released with this paper can be accessed through the IIBDGC webpage (file name: ucmeta-sumstats.txt.gz). The file contains data for 1428749 variants, their risk allele and effect size, and positions in b36. Out of these, 1406908 variants are also included in your file anderson_2011_21297633_uc_efo0000729_1_gwas.sumstats.tsv.gz (b37). The OR for those 1406908 variants in both files perfectly aligns (other than for 168 variants where OR in ucmeta-sumstats.txt.gz is >10, and in anderson_2011_21297633_uc_efo0000729_1_gwas.sumstats.tsv.gz is being set to 9.99). However, when comparing both files 672167 variants have the risk allele (and effect allele) in ucmeta-sumstats.txt.gz noted as the other allele in anderson_2011_21297633_uc_efo0000729_1_gwas.sumstats.tsv.gz.
> 
>  
> 
> When it comes to your formatted file (21297633-GCST000964-EFO_0000729-Build37.f.tsv.gz), it looks like the effect size was kept the same as in the two previous files (ucmeta-sumstats.txt.gz and anderson_2011_21297633_uc_efo0000729_1_gwas.sumstats.tsv.gz). However, the effect allele and other allele were swapped in comparison to the previous GWAS catalog file anderson_2011_21297633_uc_efo0000729_1_gwas.sumstats.tsv.gz.
> 
>  
> 
> When it comes to the formatted & harmonised file (21297633-GCST000964-EFO_0000729.h.tsv.gz), effect sizes change when compared with harmonised file (21297633-GCST000964-EFO_0000729-Build37.f.tsv.gz), but those align with the swaps made regarding the definitions of effect and alternative alleles.
> 
> Attached is the code I used to investigate this, if it can be of any help. The final part of the code compares results in gwas catalog with the published table 2 (attached is a copy of table_2). IIBDGC file aligns, but the other two files does not.

**Comment by jdhayhurst** [comment]
The “raw” file (anderson_2011_21297633_uc_efo0000729_1_gwas.sumstats.tsv.gz ) looks like it has the effect and other alleles flipped compared to the original (ucmeta-sumstats.txt.gz) - could this be our formatting error @buniello? This has consequences for the data harmonisation. Our file is b37 while theirs is b36 and our “other allele” is their “risk allele”.

**Comment by jdhayhurst** [comment]
On staging:
- pulled in "original" file from IIBDGC webpage (file name: ucmeta-sumstats.txt.gz) 
- formatted this file
- reharmonising formatted file

**Comment by sprintell** [comment]
@jdhayhurst  will check with @ljwh2  on what should be done with this, either to fix it which is going to be very demanding or probably just re-initiate

**Comment by ljwh2** [comment]
@jdhayhurst confirmed we should reharmonise their original file

**Comment by jdhayhurst** [comment]
I'm looking a replacing the file we have with their file ucmeta-sumstats.txt.gz but there are two issues. 
1. They do not have the non-risk allele in the file
2. Some of the rsIDs do not match the location data (even accounting for different genome assemblies). For example:
```
SNP CHR POS RISK COF SCAN-P OR(95%)
rs9629043 1 554636 C 0.392 0.348 1.02(0.95-1.09)
rs12244 11 111405963 A 0.999 0.772 1.01(0.40-2.57)
```
rs9629043 --> MT:4223-4223
rs12244 --> 1:42665982-42665982

Contacted user explaining this.

**Comment by ljwh2** [comment]
Retract sumstats pending communication from author

**Comment by jdhayhurst** [comment]
revoked public access. Link is obviously broken, unless we remove the sumstats flag from the curation db

**Comment by jdhayhurst** [comment]
updated study flag in db
