### ISSUE TITLE
PubMed id "17952075" missing ethnicity in 5 of 6 of its study accessions

### ISSUE THREAD

**Issue by mattcloward** [EBISPOT/gwas-user-requests#6]
See the below link:
https://www.ebi.ac.uk/gwas/publications/17952075

The study at PubMed id "17952075" has 5 study accession ids associated with it (GCST000115-GCST000120). The study title says that the ethnicity for this study is "European." However, only one of the study accession ids lists an ethnicity (GCST000118 has European listed). GCST000115, GCST000116, GCST000117, GCST000119, and GCST000120 don't have an ethnicity listed. This makes querying the database for ethnicities of all studies difficult. Can the ethnicity for these study accessions be added soon?

Thank you!

**Comment by ljwh2** [comment]
We have added the curated ancestry in the database and you should see the changes following our next data release in mid January. Thanks for bringing this to our attention.
