### ISSUE TITLE
Submitted sumstats file on ftp is incomplete

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/gwas-user-requests#60]
From gwas-info:

We're looking at the data file provided for GCST90092831 https://www.ebi.ac.uk/gwas/studies/GCST90092831 and whilst the MD5 of our downloaded file matches the hash provided, the file appears to be incomplete.

The end of the file looks like this;
jamie@yuri$ zless GCST90092831_buildGRCh37.tsv.gz | tail

gzip: GCST90092831_buildGRCh37.tsv.gz: unexpected end of file
rs117519112     T       G       0.977251        -0.00558396     0.0133791       6.8E-01
rs79628776      C       T       0.979315        -0.0221859      0.0139985       1.1E-01
rs73362132      T       A       0.928918        0.00854055      0.00779422      2.7E-01
rs202105087     G       GGT     0.976631        0.00418545      0.0133572       7.5E-01
rs430433        G       T       0.597087        -0.00216743     0.00407337      5.9E-01
rs112972698     C       T       0.993907        -0.0477409      0.0278006       8.6E-02
rs568988020     G       T       0.998913        -0.0407995      0.0616113       5.1E-01
rs9978453       G       A       0.7641  0.000653686     0.00471222      8.9E-01
rs2837442       T       A       0.897663        -0.00114605     0.00660332      8.6E-01
rs13051821      jamie@yuir$ 
jamie@yuri$
jamie@yuri$

Would you be able to ask the data submitter if they can re-upload this file?

**Comment by ljwh2** [comment]
@earlEBI Could you please investigate this, contact the submitter if necessary and work with devs to replace the file? It may be easier to switch the file manually rather than have them resubmit.

**Comment by earlEBI** [comment]
@ljwh2 This is now fixed
