### ISSUE TITLE
Corrupt data - GCST90044903

### ISSUE THREAD

**Issue by jiyue1214** [EBISPOT/gwas-user-requests#63]
Hi,

I found the [FTP download link](http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90044001-GCST90045000/GCST90044903/GCST90044903_buildGRCh37.tsv.gz) of the study GCST90044903 (PMID:34791234) is not working. Meanwhile, the summary statistic data of this study stored on Noah (/nfs/ftp/pub/databases/gwas/summary_statistics/GCST90044001-GCST90045000/GCST90044903/GCST90044903_buildGRCh37.tsv.gz) is corrupted.

**Comment by jdhayhurst** [comment]
Can confirm that the file is corrupt, both copies that we have. It must have been corrupted  during transfer between our file systems. The only way to resolve this is to have the submitter to resend the file.

**Comment by jiyue1214** [comment]
Thanks for your help. I will be responsible to contact the author then!

**Comment by ljwh2** [comment]
Hi @jiyue1214 did you contact the author for this issue or is that still to be done?

**Comment by jiyue1214** [comment]
HI @ljwh2 , I have not contacted the author. Since the author needs to re-submit the data, I was told the GWAS catalog would contact the author. Hopefully, we will get it soon.

**Comment by jdhayhurst** [comment]
replaced file on staging - should release with next sync (tonight)

**Comment by ljwh2** [comment]
@ljwh2 check if this can be closed

**Comment by ljwh2** [comment]
@jiyue1214 could you please confirm if this ticket can be closed? James has updated the file

**Comment by jiyue1214** [comment]
Hi @ljwh2, thanks for all your help! The replaced file works!
