### ISSUE TITLE
GCP ID: GCP000358 not found

### ISSUE THREAD

**Issue by Guo00158** [EBISPOT/gwas-user-requests#66]
Hi,

I was trying to locate the GWAS summary data using the GCP ID (GCP000358) provided by a recent study: https://www.nature.com/articles/s41588-022-01165-1#data-availability. But no results are related to this ID. I wonder where I can get access to it.

Thanks!

**Comment by earlEBI** [comment]
Hi, 

Thanks for getting in touch. Unfortunately the GCP ID provided in the paper is not searchable in our pages. The easiest way to access the data would be to search by PMID - which takes you to this page: https://www.ebi.ac.uk/gwas/publications/36071172 - and scroll down to the bottom studies table which contains FTP links in the right-hand column. 

Hope this helps!

**Comment by Guo00158** [comment]
Dear EBI team,

Thank you very much! It's really great to know the PMID works!

Best,
Yuxin
