### ISSUE TITLE
The title for study ID "GCST004165" has a monospace/ligated character

### ISSUE THREAD

**Issue by mattcloward** [EBISPOT/gwas-user-requests#7]
When using the API to download data, I found that the title for study ID ""GCST004165" has a ligated `ﬁ` character when the character should be separated into two characters, "f" and "i"
The offending character can be found in the word "identifies."

**Comment by eks-ebi** [comment]
I've looked into fixing this and found that the incorrect `ﬁ` character is there in our curation app. Unfortunately, the curation app doesn't allow direct editing of publication titles - they are imported from EuropePMC and locked. It's likely that the strange character was already present in EuropePMC.

Can one of the developers edit the publication title directly in the database? @sprintell

**Comment by jdhayhurst** [comment]
Updated in the database: replaced `ﬁ` with `fi` in the study title for GCST004165. The change will be published with the next data release.
