### ISSUE TITLE
reformat and reharmonise GCST006980

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-user-requests#76]
GCST006980 has been incorrectly formatted with the OR field being mapped to the wrong field. 
steps: 

- [ ] remove incorrect files from FTP
- [ ] reformat
- [ ] harmonise reformatted file

**Comment by ljwh2** [comment]
Lizzy to do this

**Comment by jdhayhurst** [comment]
- reformat and name according to GCST<ID>.tsv.gz conv with -meta.yaml file in parent directory on staging (pre-GWAS-SSF). This will then be auto be picked up by the v0 harmonisation pipeline.

**Comment by earlEBI** [comment]
Done:
- removed the old harmonised directory on public
- reformatted the raw file to the pre-GWAS-SSF standard format with correct header for OR. - on staging
- created yaml file. - on staging
Should be released to pub overnight and added to harmonisation queue.

**Comment by earlEBI** [comment]
The files did not sync to public overnight.

**Comment by ljwh2** [comment]
@sajo-ebi to investigate why files did not get released

**Comment by earlEBI** [comment]
Sumstats have now been released to pub (fixed along with the ftp sync issue)
