### ISSUE TITLE
File corrupt GCST004422 (PMID: 27989323) 

### ISSUE THREAD

**Issue by Nevarill** [EBISPOT/gwas-user-requests#78]
I found a link http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST004001-GCST005000/GCST004422/harmonised/27989323-GCST004422-EFO_0004762.h.tsv.gz (PMID: 27989323) where the file appears to be truncated (filesize suspiciously small) and gives error by unzipping. I reckon maybe failed upload here.

**Comment by ljwh2** [comment]
@earlEBI could you please look into this?

**Comment by earlEBI** [comment]
I couldn't see an obvious reason why this harmonised file is corrupted but agree it is truncated unexpectedly. 
I've deleted the harmonised file, renamed the formatted file and created a metadata yaml file so that it should re-enter the harmonisation pipeline.

**Comment by ljwh2** [comment]
Leaving ticket open for confirmation when hm pipeline has been run

**Comment by ljwh2** [comment]
@jiyue1214 to prioritise for hm

**Comment by jiyue1214** [comment]
GCST004422 has been harmonized and all chromosomes exist. The file size (166M) is similar to the unharmonized file (155M). The ticket can be closed.
