### ISSUE TITLE
GCST000964 summary statistics has swapped effect allele and other allele columns

### ISSUE THREAD

**Issue by sabrinacamp2** [EBISPOT/gwas-user-requests#8]
Hi,

I was looking through the formatted summary statistics for this study (ftp://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/AndersonCA_21297633_GCST000964/harmonised/21297633-GCST000964-EFO_0000729-Build37.f.tsv.gz), and found that there were two headers in the file. One header was found at the beginning and another was found 2/3 down the file. The difference between these two headers was the column position of the `effect allele` and the `other allele` (picture attached). 

To try and see which format is correct, I went to the original summary statistics (ftp://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/AndersonCA_21297633_GCST000964/anderson_2011_21297633_uc_efo0000729_1_gwas.sumstats.tsv.gz) and concluded that the formatted file has swapped the effect and other allele (picture attached). 

Could you confirm if this is the case? 

All the best,
Sabrina Camp 
<img width="378" alt="Screen Shot 2021-01-08 at 12 24 08 PM" src="https://user-images.githubusercontent.com/52207849/104052398-aab84480-51b7-11eb-8f82-ecf996cd61f5.png">
![githubissue_gwassummary](https://user-images.githubusercontent.com/52207849/104052399-aab84480-51b7-11eb-9940-9c21d8128a35.png)

**Comment by jdhayhurst** [comment]
@buniello please could you check the allele columns for this study?

**Comment by buniello** [comment]
@jdhayhurst the file has now been re-formatted with the new tool and also ss-validated. It's in the "NewStudies" directory ready for harmonisation.

**Comment by jdhayhurst** [comment]
Perfect! Thanks @buniello

**Comment by jdhayhurst** [comment]
fixed and released
