### ISSUE TITLE
The harmonised summary statistics list contains data not available.

### ISSUE THREAD

**Issue by DSuveges** [EBISPOT/gwas-user-requests#80]
Hi Guys, 

The [list of harmonised summary statistics](https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/harmonised_list.txt) on ftp contains a study that is not available (`./GCST000001-GCST001000/GCST000964/harmonised/21297633-GCST000964-EFO_0000729.h.tsv.gz`). I guess it has been retracted or was put under embargo. I'm wondering if there's a mechanism to update the list reflecting these updates.

Thanks.

**Comment by ljwh2** [comment]
@earlEBI please could you investigate and remove the harmonised file if appropriate?

**Comment by earlEBI** [comment]
This was a file which had a discrepancy. Author was contacted but did not reply so the link in UI was removed but the folder was not hidden. 
I've now hidden GCST000964 on staging and removed (including harmonised subfolder) from public FTP and harmonised files list.

**Comment by DSuveges** [comment]
Thank you guys!
