### ISSUE TITLE
Some studies are showing up in search, but are not loading

### ISSUE THREAD

**Issue by DSuveges** [EBISPOT/gwas-user-requests#81]
Hi,

There's this study accession: `GCST90271955` (also `GCST90274714`, `GCST90277870`, `GCST90277997` etc)

If I search for it on the UI, I can see the study: 
![image](https://github.com/EBISPOT/gwas-user-requests/assets/7122521/e982dfd4-aee2-4270-829a-b76196ccbd36)

However if you click, it won't load:
![image](https://github.com/EBISPOT/gwas-user-requests/assets/7122521/e8c08a4a-5dca-4aa0-a48e-5888951db31a)

I don't think if this was a browser or cache related issue, I managed to replicate it on different browsers. I assume this study is in pre-publication, that's why I could find the harmonised summary statistics on ftp (also the study is in the harmonised list on ftp), but not in the actual study index in the download files. Given until we have the complete metadata for a study, it is not possible to properly contextualise the contents of the summary statistics, is there a way to kind of "hide" these studies completely until curation?

Also somewhat related: looking at these studies, some are actually showing up in the study page with a pre-publication title. Looking at these titles, apparently some of them have already been published. I'm wondering if you are planning to prioritise these publications for curation?

Some examples:

- [GCST90267986](https://www.ebi.ac.uk/gwas/studies/GCST90267986) is now published: [37601967](https://pubmed.ncbi.nlm.nih.gov/37601967/)
- [GCST90270327](https://www.ebi.ac.uk/gwas/studies/GCST90270327) is now published: [37973980](https://www.nature.com/articles/s41467-023-43237-8)
- [GCST90271557](https://www.ebi.ac.uk/gwas/studies/GCST90271557) is now published: [37679419](https://www.nature.com/articles/s41588-023-01462-3)
- [GCST90271641](https://www.ebi.ac.uk/gwas/studies/GCST90271641) is now published: [37415806](https://pubmed.ncbi.nlm.nih.gov/37415806/) 
- [GCST90281273](https://www.ebi.ac.uk/gwas/search?query=GCST90281273) is now published: [37919453](https://pubmed.ncbi.nlm.nih.gov/37919453/)

**Comment by ljwh2** [comment]
Thanks Daniel, we will investigate.

> Given until we have the complete metadata for a study, it is not possible to properly contextualise the contents of the summary statistics, is there a way to kind of "hide" these studies completely until curation?

Would it help to have a column in the list of harmonised files saying whether it has been curated or not? We didn't used to harmonise prepublished files, but this was requested by other users.

**Comment by DSuveges** [comment]
> We didn't used to harmonise prepublished files, but this was requested by other users.

That is a very strange request. What do they do with these summary statistics files if they don't know what is the trait or other metdata?

> Would it help to have a column in the list of harmonised files saying whether it has been curated or not?

I'm not sure. Let's leave as it is given it was a user requests, we'll make our pipelines resilient for this.

**Comment by ljwh2** [comment]
@DSuveges it's true there is no EFO term for the prepublished studies, but the reported trait is available, and all the mandatory study & sample metadata. After publication curators add the top associations and EFO (and any additional non-mandatory metadata mentioned in the paper).

**Comment by DSuveges** [comment]
You are right: I just realised there's a different file for studies with pre-published manuscripts... That's why I was not seeing any matching metdata because I was only looking at the `gwas-catalog-download-studies-v1.0.3.1.txt` table. However, I would still say it is quite strange that these studies show up on the search page, but their links to the study page doesn't work.

**Comment by ljwh2** [comment]
Yes that's an error, we are investigating.

**Comment by ljwh2** [comment]
For the prepub landing pages not loading intermittently, there is a separate ticket goci#1200.

For the submissions not inked to a PMID that you mentioned, one was assigned negative by our literature search and the others are in progress through the curation workflow. We picked up a few more where the PMIDs were never included in the literature search and we will follow up with LitSuggest developers to find out why. Thanks for flagging these. 

Thanks for flagging these @DSuveges
