### ISSUE TITLE
Download link on the UI doesn't work for unpublished study and ancestry tables

### ISSUE THREAD

**Issue by DSuveges** [EBISPOT/gwas-user-requests#84]
As the title suggests: On the downloads page (`https://www.ebi.ac.uk/gwas/docs/file-downloads`), the links to download unpublished studies (`https://www.ebi.ac.uk/gwas/api/search/downloads/unpublished_studies/v1.0.3.1`) and unpublished ancestries (`https://www.ebi.ac.uk/gwas/api/search/downloads/unpublished_ancestries/v1.0.3.1`)  lead to `HTTP Status 404 - File not found for download`

**Comment by ljwh2** [comment]
@ala-ebi to check after current DR

**Comment by ala-ebi** [comment]
this is now fixed @DSuveges, thanks for reporting!
