### ISSUE TITLE
Trait column names are inconsistent in the download files

### ISSUE THREAD

**Issue by DSuveges** [EBISPOT/gwas-user-requests#85]
I think the column names are supposed to be consistent between the published and unpublished studies given both from the same version. However this is not the case. As I'm reading  both files at the same time assuming the same schema, this casuses some headache. Please see example:

```bash
UNPUBLISHED_STUDIES=ftp://ftp.ebi.ac.uk/pub/databases/gwas/releases/2023/12/21/gwas-catalog-unpublished-studies-v1.0.3.1.tsv
STUDIES=ftp://ftp.ebi.ac.uk/pub/databases/gwas/releases/2023/12/21/gwas-catalog-download-studies-v1.0.3.1.txt

paste -d"\t" <(curl -s $STUDIES | head -n1 | tr "\t" "\n" | sort) \
  <(curl -s $UNPUBLISHED_STUDIES | head -n1 | tr "\t" "\n" | sort) \
  | awk -F"\t" '$1 != $2' | column -t -s$'\t'
```

giving:

```
MAPPED_TRAIT      MAPPED TRAIT
MAPPED_TRAIT_URI  MAPPED TRAIT URI
```

Although the unpublished study table has no mapped trait information, this discrepancy makes the automatic loading problematic.

**Comment by ljwh2** [comment]
Code changes made, should be visible after next DR

**Comment by DSuveges** [comment]
Great to hear. Thank you all!

**Comment by ljwh2** [comment]
reopening until we've verified in the DR

**Comment by sprintell** [comment]
@ala-ebi  will double-check this

**Comment by ala-ebi** [comment]
@DSuveges "MAPPED TRAIT" and "MAPPED TRAIT URI" are now "MAPPED_TRAIT" and "MAPPED_TRAIT_URI" respectively in unpublished studies
