### ISSUE TITLE
Missing A2 information from GWAS study table

### ISSUE THREAD

**Issue by luotian0911** [EBISPOT/gwas-user-requests#86]
Hi everyone, I have noticed that the txt document for Study accession GCST009131 (Pub. date: 2019-10-31) available at the FTP download link (http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST009001-GCST010000/GCST009131/Lopez-Isac_prePMID_META_GWAS_SSc.meta.txt) is missing information. Specifically, the A2 information column lacks detailed content and is displayed with question marks, as shown in the image below.

**Comment by luotian0911** [comment]
![Uploading SSc.jpg…]()

**Comment by ljwh2** [comment]
Unfortunately we do not have any data about the A2 allele in this dataset. The summary statistics were provided to us by the author as you see them (without the A2 allele), so we don’t have any further details to provide.

I would recommend contacting the corresponding author of the original paper to try to get the missing allele information.

Please note that this dataset was submitted to the GWAS Catalog before our current standard format was introduced, and did not go through the same rigorous QC requirements as more recent submissions. We now require effect_allele and other_allele for all submissions.

Sorry we can’t help further in this case.
