### ISSUE TITLE
Duplicate data in trait mappings file due to invisible UTF-8 character.

### ISSUE THREAD

**Issue by spiros** [EBISPOT/gwas-user-requests#87]
I was trying to load `gwas_catalog_trait-mappings_r2024-07-27.tsv` in a MySQL table and the uniquness constraint kept failing. 

I tracked down the issue to a duplicate entry for the `Complement C5 levels` entry (http://www.ebi.ac.uk/efo/EFO_002027) - one row has a [\<FEFF\>](https://www.compart.com/en/unicode/U+FEFF) character (in the word 'Complement') and the other one does not:

```
Complement C5 levels    complement C5 measurement       http://www.ebi.ac.uk/efo/EFO_0020278    Other measurement       http://www.ebi.ac.uk/efo/EFO_0001444
C<feff>omplement C5 levels      complement C5 measurement       http://www.ebi.ac.uk/efo/EFO_0020278    Other measurement       http://www.ebi.ac.uk/efo/EFO_0001444
```

Upon inspection, `<FEFF>` is present in other values in the file as well e.g. 

``` 
Total cholesterol in IDL meal response (<feff>OrNLSr)
Triglycerides levels in very large VLDL meal response (<feff>OrNLSr)
```

**Comment by ljwh2** [comment]
@eks-ebi to investigate whether this can be fixed on the curation side

**Comment by eks-ebi** [comment]
I've been able to select and copy the `<FEFF>` character in one of the offending entries in the reported traits list (in depocuration app). Searching for the character reveals 109 affected reported traits, so should be a manageable number to deal with. Plan is:

- [x] edit the traits to remove `<FEFF>` wherever possible (it won't let me save them if this results in a duplicate trait name)

- [x] if it causes duplicates, find the studies annotated with the affected trait names and recurate them, then delete the duplicate traits containing `<FEFF>`

**Comment by eks-ebi** [comment]
Traits that could not be edited (tick when fixed at submission level):

- [x]  C`<FEFF>`omplement C5 levels - problematic entry is in GCST90094399 (PMID 34339498)
- [x]  Omega-3 fatty acids meal response (`﻿<FEFF>`OrNLSr) - problematic entry is in GCST90095322 (PMID 34610981)
- [x]  Triglycerides levels in large VLDL meal response (`﻿<FEFF>`OrNLSr) - problematic entry is in GCST90095224 (PMID 34610981)

**Comment by eks-ebi** [comment]
Edits have all been done and studies are re-published in the Catalog, so the problem should be fixed after the next data release

**Comment by eks-ebi** [comment]
@ljwh2 Just to let you know that this ticket is completed now, but I can't move it to Done (don't have the permissions for this repository)

**Comment by eks-ebi** [comment]
confirmed in staging

**Comment by ljwh2** [comment]
@spiros Thanks for flagging this issue to us, you should see the corrected data in production by the end of today.

**Comment by spiros** [comment]
no problem, happy to help, this one was fun to track down :)
